version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/emailservice
permissions:
  - object: /home/ubuntu/emailservice/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: /start.sh
      timeout: 900
      runas: ubuntu