version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
    - echo "Email service pre-build phase"
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
    - echo "Email service build phase"
    - mvn clean install
    - docker build --tag "895164885144.dkr.ecr.eu-west-1.amazonaws.com/qbthonspartanemail:${TAG}" .
  post_build:
    commands:
    - echo "Email service post-build phase"
    - docker push "895164885144.dkr.ecr.eu-west-1.amazonaws.com/qbthonspartanemail:${TAG}"
    - cp ./email-deployment.yml email-deployment_temp.yml  
    - sed -i s/TAG_ID/$TAG/g email-deployment_temp.yml
artifacts:
  files:
   - '**/*'