package com.ent.qbthon.email.entity;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@DynamoDBTable(tableName = "QBTHON_USER_EVENT")
@Data
public class UserEvent implements Serializable {
	/**
	* 
	*/
	private static final long serialVersionUID = 1L;

	@DynamoDBHashKey(attributeName = "user_event_id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute(attributeName = "user_id")
	private String userId;

	@DynamoDBAttribute(attributeName = "event_id")
	private String eventId;

	@DynamoDBAttribute(attributeName = "reminder_flag")
	private boolean reminderFlag;

	@DynamoDBAttribute(attributeName = "amount")
	private int amount;

	@DynamoDBAttribute(attributeName = "role")
	private String role;

	@DynamoDBAttribute(attributeName = "nominated")
	private boolean nominated;

}
